behaviors:
  CarAgentTraining:
    trainer_type: ppo
    hyperparameters:
      batch_size: 120
      buffer_size: 12000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      ##imitation learning with gail
      gail:
        gamma: 0.99
        strength: 0.5
        demo_path: "C:/eindproject-V-R_Fast/V R Fast/Demos/KartAgentDemo_1.demo"
      #imitation learning with behavioral_cloning
    # behavioral_cloning:
    #   strength: 0.5
    #   demo_path: "C:/eindproject-V-R_Fast/V R Fast/Demos/KartAgentDemo_1.demo"
    keep_checkpoints: 5
    max_steps: 500000000
    time_horizon: 1000
    summary_freq: 12000
    threaded: true
